name: Sync Label Config

on:
  push:
    paths:
      - '.github/labels.yml'
  workflow_dispatch:

jobs:
  sync-labels:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: EndBug/label-sync@v1
        with:
          config-file: .github/labels.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          delete-other-labels: true
